### ISSUE TITLE
can't make snap

### ISSUE THREAD

**Issue by danbjoseph** [ericfischer/osm-animate#1]
On a Mac. I get the following error when following the readme instructions.

```
» make snap
make: *** No rule to make target `snap'.  Stop.
```

Any chance you know what I may be doing wrong?

(I'm working with this for Tyler Radford.)

**Comment by danbjoseph** [comment]
got https://github.com/ericfischer/osm-snap.git and was able to create a dar-es-salaam_tanzania.snap file and a dar-es-salaam_tanzania.dm folder with files inside

now stuck at the `./perform dar-es-salaam_tanzania` step
get a 'No such file or directory' error

**Comment by danbjoseph** [comment]
i'm an idiot. need to clone the osm-animate repo first and then start following the readme while inside the osm-animate folder.

**Comment by e-n-f** [comment]
Sorry for the confusing instructions! Glad you got it working.
